server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  host: 'localhost'
  username: 'postgres'
  password: 'password'
  database: 'nestsocial'

jwt:
  expiresIn: 3600
  secret: 'topTestSecretHash'